### ISSUE TITLE
Test fails on Windows as of 2016.11

### ISSUE THREAD

**Issue by stmuk** [softmoth/p6-Template-Mustache#15]
```
===> Testing: Template::Mustache:auth('github:softmoth')
# Reading spec files from '../mustache-spec/specs'
read from dirhandle failed: 3
  in sub load-specs at C:\Users\steve\star\rakudo-star-2016.12.zef\modules\p6-Template-Mustache\t\lib\Template\Mustache\TestUtil.pm (Template::Mustache::TestUtil) line 11
  in block <unit> at t/91-specs.t line 8

# Reading spec files from '../mustache-spec/specs'
read from dirhandle failed: 3
  in sub load-specs at C:\Users\steve\star\rakudo-star-2016.12.zef\modules\p6-Template-Mustache\t\lib\Template\Mustache\TestUtil.pm (Template::Mustache::TestUtil) line 11
  in block <unit> at t/92-specs-file.t line 19

===> Testing [FAIL]: Template::Mustache:auth('github:softmoth')
```

**Comment by softmoth** [comment]
Steve, I'm not sure where the problem is coming from here. Maybe you could help dig into what's misbehaving? The code is depending on `dir('foo')` to `fail` if there is a problem. For example,

    dir('nonexistent-dir') // <a b c>   # This should be (a b c), not an error

I assume some part of that isn't working on your system, but I'm not sure what it is or just how to work around it. If you can find a workaround, let me know.

**Comment by stmuk** [comment]
Your above code fragment does error on Windows.
I only fire up my Windows VM very rarely but you might find adding a file like 

https://github.com/tadzik/Task-Star/blob/master/appveyor.yml

is helpful for debugging on that system.  

The debug cycle using Windows CI  is a little slow but can be speeded up by adding "choco install rakudo-star" (or similar) and trying to "zef --force install" your module. 

It could be a bug in Rakudo itself of course...

**Comment by softmoth** [comment]
Now passing on appveyor: https://ci.appveyor.com/project/softmoth/p6-template-mustache

Thank you!!!
