### ISSUE TITLE
Template Mustache is test fails while installing Bailador

### ISSUE THREAD

**Issue by nige123** [softmoth/p6-Template-Mustache#20]
Hi,

Recently got this error when install Bailador on 2017.06 and 2017.07.

Please see below ...

===> Testing [OK] for Template::Mojo:ver('0.1')
===> Testing: Template::Mustache:auth('github:softmoth')

# Failed test 'Inline partial can get filesystem partial'
# at t/03-cascade.t line 56
# expected: 'Say Hello, Jimmy.
# , and find me a Hello, Jimmy.
# '
#      got: 'Say , and find me a '
# Looks like you failed 1 test of 5
# Reading spec files from '../mustache-spec/specs'
# Reading spec files from '../mustache-spec/specs'

===> Testing [FAIL]: Template::Mustache:auth('github:softmoth')
Aborting due to test failure: Template::Mustache:auth('github:softmoth') (use --force-test to override)

**Comment by softmoth** [comment]
Thank you for reporting this problem. I'm not able to reproduce it; install via `zef` works, both alone and as a dependency of Bailador. Hopefully it was a transient issue in zef or rakudo and is OK now. But if you find any problem or see a way to make it more robust let me know. It would help to run the failing test directly with something like `perl6 -Ilib t/03-cascade.t`, to get more verbose output. Thanks!
