### ISSUE TITLE
Tag names can only contain what is considered an <ident>

### ISSUE THREAD

**Issue by SyrupThinker** [softmoth/p6-Template-Mustache#26]
Because of this tags containing dashes (and other non \<ident\> characters)
will not be substituted, as can be seen here:
```
> perl6 -e 'use Template::Mustache; Template::Mustache.render(\'{{base00-hex}}\', { \'base00-hex\' => 1 }).say'
# OUTPUT: «{{base00-hex}}␤»
```

The spec leaves this point somewhat open,
but the discussion in https://github.com/mustache/spec/issues/67 suggests that it can basically contain anything
that isn't interpreted in some other way (minus whitespace).

The way I see it the following token, and possibly ones using it, would need to be changed.
https://github.com/softmoth/p6-Template-Mustache/blob/5ad705e3b2e30fbc1cb9ae6590c49c7db7b51167/lib/Template/Mustache.pm#L31

**Comment by softmoth** [comment]
Thank you for the report & PR.
