### ISSUE TITLE
Triple Mustache doesn't work when the field name contains a minus

### ISSUE THREAD

**Issue by holli-holzer** [softmoth/p6-Template-Mustache#29]
say Template::Mustache.render('{{{ bar-x }}}', %(:bar-x) ); # '{True}', should be 'True'
    say Template::Mustache.render('{{{ bar }}}', %(:bar) );     # 'True', works as expected

Boy, that took me a while to figure out.

**Comment by finanalyst** [comment]
I looked at this superficially. 'bar-x' should be identified as a name and treated the same way as 'bar'. It is not immediately clear where the extra { } are being added.

**Comment by softmoth** [comment]
Fixed in fbf80dc
