### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by elohmrow** [softmoth/p6-Template-Mustache#8]
rakudo-star-2015.07/install/bin/perl6-m --target=mbc --output=rakudo-star-2015.07/install/share/perl6/lib/Template/Mustache.pm.moarvm rakudo-star-2015.07/install/share/perl6/lib/Template/Mustache.pm
Saw 1 occurrence of deprecated code.

$*PROGRAM_NAME seen at:
rakudo-star-2015.07/install/share/perl6/lib/Template/Mustache.pm, line 184
Deprecated since v2015.6, will be removed with release v2015.9!
Please use $*PROGRAM-NAME instead.

Please contact the author to have these occurrences of deprecated code
adapted, so that this message will disappear!

Please note that ALL deprecated features will be removed at the RC-0 release
(expected September 2015).

**Comment by softmoth** [comment]
Thanks for the issue report. This was fixed by pull request #6 .
